// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart' as dotenv;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _android;
  static FirebaseOptions get android {
    if (_android != null) return _android;

    final String apiKey = dotenv.env['API_KEY'];

    _android = FirebaseOptions(
      apiKey: apiKey,
      appId: '1:576452479107:android:a2b44be6f32a40e323f3b6',
      messagingSenderId: '576452479107',
      projectId: 'forbidden-lands-9083c',
      storageBucket: 'forbidden-lands-9083c.appspot.com',
    );
    return _android;
  }

  static FirebaseOptions _ios;
  static FirebaseOptions get ios {
    if (_ios != null) return _ios;

    final String apiKey = dotenv.env['PROJECT_KEY'];

    _ios = FirebaseOptions(
      apiKey: apiKey,
      appId: '1:576452479107:ios:a8a736fac89e67d723f3b6',
      messagingSenderId: '576452479107',
      projectId: 'forbidden-lands-9083c',
      storageBucket: 'forbidden-lands-9083c.appspot.com',
      iosClientId: '576452479107-t4i3tjh367crp2ruddj41c6b79s2jb1j.apps.googleusercontent.com',
      iosBundleId: 'com.example.forbiddenLands',
    );
    return _ios;
  }
}
